build:
  version: "3.0"

accounts:
  message: "ACCOUNT LOCAL 1 "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
